apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
    version: 2.6.2
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector: 
    app: myapp
    version: 2.6.2
    
